name: AWS Assume Role
description: Assumes an IAM Role before running the build command.
author: https://github.com/cultureamp
requirements:
  - aws
configuration:
  properties:
    duration:
      type: string
    role:
      type: string
    region:
      type: string
  required:
    - role
  additionalProperties: false
