steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files:
          - hooks/**

  - label: ":shell: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: weillcomecollection/aws-assume-role

  - label: ":shell: Tests"
    plugins:
      docker-compose#v2.2.0:
        run: tests
