steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files:
          - hooks/**
    agents:
      queue: seedrs-platform-staging

  - label: ":shell: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: seedrs/aws-assume-role
    agents:
      queue: seedrs-platform-staging

  - label: ":shell: Tests"
    plugins:
      docker-compose#v2.5.1:
        run: tests
    agents:
      queue: seedrs-platform-staging
